pspsh: fix build error with musl libc
pspsh.cpp:133:43: error: 'strcmp' was not declared in this scope
pspsh.cpp:188:18: error: 'strlen' was not declared in this scope
pspsh.cpp:197:26: error: 'strchr' was not declared in this scope
pspsh.cpp:201:37: error: 'memmove' was not declared in this scope
pspsh.cpp:257:34: error: 'strcpy' was not declared in this scope
etc.

since musl enforces clean namespace, string.h doesn't get automatically
included as a "drive-by", unlike in GLIBC.